services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest # SQL Server image
    container_name: Usersqlserver
    ports:
      - "1433:1433" # Expose SQL Server's port
    environment:
      SA_PASSWORD: "ByeBye.123" # Set the SA password
      ACCEPT_EULA: "Y" # Accept the EULA
    volumes:
      - sqlserver_data:/var/opt/mssql # Persist database data in a volume

  userserviceapi:
    image: gnegash/userservice
    container_name: UserService
    ports:
      - "8088:8088" # Expose your API on port 8080
    depends_on:
      - sqlserver # Ensure SQL Server starts first
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=MicroServiceDb;User Id=sa;Password=ByeBye.123;TrustServerCertificate=True;" # Connection string to SQL Server
      ASPNETCORE_URLS: "http://+:8088"

volumes:
  sqlserver_data: # Define the volume to persist SQL Server data
